linters:
  enable:
    - errorlint
    - forcetypeassert
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - importas
    - makezero
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - unparam
    - wastedassign
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - testpackage
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
